name: PR CICD
on: 
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: Pip install package
        run: |
          python -m pip install --upgrade pip
          pip install .
      - name: Poetry install package
        run: |
          pip install poetry
          poetry install
      - name: Linting
        run: |
          poetry run pydocstyle --convention=google
          poetry run isort . --check
          poetry run black . --check
          poetry run flake8 . --ignore E501,F401,W503 --count
        continue-on-error: True
      - name: Testing
        run: |
          poetry run pytest