name: PR CICD
on:
  pull_request:
    branches:
      - master
    types:
      - opened
      - edited
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to test'
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          cache: 'poetry'
      - name: Pip install package
        run: |
          python -m pip install --upgrade pip
          pip install .
      - name: Poetry install package
        run: |
          pip install poetry
          poetry install
    lint:
      name: Linting
      uses: ./.github/workflows/linting.yaml
    test:
      name: Testing
      uses: ./.github/workflows/testing.yaml