name: Push to Master CICD
on: 
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Pip install package
        run: |
          python -m pip install --upgrade pip
          pip install .
      - name: Poetry install package
        run: |
          pip install poetry
          poetry install
  lint:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: pydocstyle
        run: poetry run pydocstyle --convention=google
      - name: isort
        run: poetry run isort . --check
      - name: black
        run: poetry run black . --check
      - name: flake8
        run: poetry run flake8 . --ignore E501,F401,W503 --count
        continue-on-error: True
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Testing
        run: |
          poetry run pytest 