name: Push to Master CICD
on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to test'
        required: true
jobs:
  push_master:
    uses: ./.github/workflows/build.yaml
