name: Push to Master CICD
on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to test'
        required: true
jobs:
  build:
    uses: ./.github/workflows/build.yaml
  lint:
    needs: [build]
    uses: ./.github/workflows/lint.yaml
