name: Testing

on: [workflow_call]
jobs:
  test:
    runs-on: ubuntu-latests
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          cache: 'poetry'
      - name: HamiltonianBuilder
        run: poetry run pytest tests/test_builder.py
      - name: NbedDriver
        run: poetry run pytest tests/test_driver.py
      - name: Embed
        run: poetry run pytest tests/test_embed.py
      - name: HamiltonianConverter
        run: poetry run pytest tests/test_ham_converter.py
      - name: Localizers
        run: poetry run pytest tests/test_localizers.py